CREATE DATABASE IF NOT EXISTS click_to_chat_manager
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE click_to_chat_manager;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'client',
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    last_login_at DATETIME NULL,
    password_changed_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_users_role_status (role, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS widgets (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    public_key VARCHAR(100) NOT NULL UNIQUE,
    widget_name VARCHAR(190) NOT NULL,
    website_domain VARCHAR(255) NOT NULL,
    allow_www TINYINT(1) NOT NULL DEFAULT 1,
    allow_subdomains TINYINT(1) NOT NULL DEFAULT 0,
    domain_lock_enabled TINYINT(1) NOT NULL DEFAULT 1,
    strict_domain_check TINYINT(1) NOT NULL DEFAULT 1,
    whatsapp_country_code VARCHAR(8) NOT NULL DEFAULT '+60',
    whatsapp_number VARCHAR(32) NOT NULL,
    use_random_numbers TINYINT(1) NOT NULL DEFAULT 0,
    random_numbers_json LONGTEXT NULL,
    prefilled_message TEXT NULL,
    call_to_action VARCHAR(120) NOT NULL DEFAULT 'WhatsApp us',
    desktop_style VARCHAR(40) NOT NULL DEFAULT 'style-1',
    mobile_style VARCHAR(40) NOT NULL DEFAULT 'style-1',
    desktop_position_type VARCHAR(20) NOT NULL DEFAULT 'fixed',
    mobile_position_type VARCHAR(20) NOT NULL DEFAULT 'fixed',
    desktop_vertical_position_type VARCHAR(20) NOT NULL DEFAULT 'bottom',
    desktop_vertical_position_value VARCHAR(32) NOT NULL DEFAULT '25px',
    desktop_horizontal_position_type VARCHAR(20) NOT NULL DEFAULT 'right',
    desktop_horizontal_position_value VARCHAR(32) NOT NULL DEFAULT '25px',
    mobile_vertical_position_type VARCHAR(20) NOT NULL DEFAULT 'bottom',
    mobile_vertical_position_value VARCHAR(32) NOT NULL DEFAULT '25px',
    mobile_horizontal_position_type VARCHAR(20) NOT NULL DEFAULT 'right',
    mobile_horizontal_position_value VARCHAR(32) NOT NULL DEFAULT '25px',
    same_mobile_desktop_settings TINYINT(1) NOT NULL DEFAULT 1,
    desktop_open_link_type VARCHAR(20) NOT NULL DEFAULT 'new_tab',
    mobile_open_link_type VARCHAR(20) NOT NULL DEFAULT 'new_tab',
    desktop_url_structure VARCHAR(30) NOT NULL DEFAULT 'wa_me',
    mobile_url_structure VARCHAR(30) NOT NULL DEFAULT 'wa_me',
    custom_url TEXT NULL,
    show_desktop TINYINT(1) NOT NULL DEFAULT 1,
    show_mobile TINYINT(1) NOT NULL DEFAULT 1,
    show_global TINYINT(1) NOT NULL DEFAULT 1,
    business_hours_mode VARCHAR(30) NOT NULL DEFAULT 'always_open',
    business_hours_json LONGTEXT NULL,
    offline_message VARCHAR(255) NOT NULL DEFAULT 'We are currently offline. Please leave us a message later.',
    greeting_enabled TINYINT(1) NOT NULL DEFAULT 1,
    greeting_title VARCHAR(160) NULL,
    greeting_message TEXT NULL,
    greeting_delay_seconds INT UNSIGNED NOT NULL DEFAULT 2,
    greeting_capture_phone TINYINT(1) NOT NULL DEFAULT 0,
    greeting_phone_required TINYINT(1) NOT NULL DEFAULT 1,
    greeting_force_phone_capture TINYINT(1) NOT NULL DEFAULT 0,
    greeting_phone_placeholder VARCHAR(100) NOT NULL DEFAULT 'Enter your phone number',
    greeting_submit_text VARCHAR(100) NOT NULL DEFAULT 'Continue to WhatsApp',
    greeting_lead_success_message VARCHAR(255) NOT NULL DEFAULT 'Redirecting to WhatsApp...',
    custom_css LONGTEXT NULL,
    custom_script_head LONGTEXT NULL,
    custom_script_body LONGTEXT NULL,
    custom_script_footer LONGTEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_widgets_user_id (user_id),
    INDEX idx_widgets_public_lookup (id, public_key),
    CONSTRAINT fk_widgets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS widget_leads (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    widget_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    visitor_phone VARCHAR(50) NOT NULL,
    visitor_country_code VARCHAR(10) NULL,
    visitor_full_phone VARCHAR(50) NOT NULL,
    source_domain VARCHAR(255) NULL,
    source_url TEXT NULL,
    page_title VARCHAR(255) NULL,
    whatsapp_redirect_url TEXT NULL,
    ip_address VARCHAR(100) NULL,
    user_agent TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_widget_leads_widget_id (widget_id),
    INDEX idx_widget_leads_user_id (user_id),
    INDEX idx_widget_leads_visitor_phone (visitor_full_phone),
    INDEX idx_widget_leads_created_at (created_at),
    CONSTRAINT fk_widget_leads_widget FOREIGN KEY (widget_id) REFERENCES widgets(id) ON DELETE CASCADE,
    CONSTRAINT fk_widget_leads_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO users (id, name, email, password, role, status)
VALUES
    (1, 'Demo Client', 'demo@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi', 'client', 'active')
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    email = VALUES(email),
    role = VALUES(role),
    status = VALUES(status);

INSERT INTO widgets (
    id,
    user_id,
    public_key,
    widget_name,
    website_domain,
    allow_www,
    allow_subdomains,
    domain_lock_enabled,
    strict_domain_check,
    whatsapp_country_code,
    whatsapp_number,
    use_random_numbers,
    random_numbers_json,
    prefilled_message,
    call_to_action,
    desktop_style,
    mobile_style,
    desktop_position_type,
    mobile_position_type,
    desktop_vertical_position_type,
    desktop_vertical_position_value,
    desktop_horizontal_position_type,
    desktop_horizontal_position_value,
    mobile_vertical_position_type,
    mobile_vertical_position_value,
    mobile_horizontal_position_type,
    mobile_horizontal_position_value,
    same_mobile_desktop_settings,
    desktop_open_link_type,
    mobile_open_link_type,
    desktop_url_structure,
    mobile_url_structure,
    custom_url,
    show_desktop,
    show_mobile,
    show_global,
    business_hours_mode,
    business_hours_json,
    offline_message,
    greeting_enabled,
    greeting_title,
    greeting_message,
    greeting_delay_seconds,
    custom_css,
    custom_script_head,
    custom_script_body,
    custom_script_footer
)
VALUES (
    1,
    1,
    'demo_public_key_change_me_1234567890abcdef',
    'Demo Website Widget',
    'example.com',
    1,
    0,
    1,
    1,
    '+60',
    '123456789',
    1,
    '[{"country_code":"+60","number":"123456789"},{"country_code":"+60","number":"198765432"}]',
    'Hello {site}\nLike to know more information about {title}, {url}',
    'WhatsApp us',
    'style-1',
    'style-3-large',
    'fixed',
    'fixed',
    'bottom',
    '25px',
    'right',
    '25px',
    'bottom',
    '18px',
    'right',
    '18px',
    0,
    'new_tab',
    'new_tab',
    'wa_me',
    'wa_me',
    NULL,
    1,
    1,
    1,
    'always_open',
    '{"monday":{"enabled":true,"open":"09:00","close":"18:00"},"tuesday":{"enabled":true,"open":"09:00","close":"18:00"},"wednesday":{"enabled":true,"open":"09:00","close":"18:00"},"thursday":{"enabled":true,"open":"09:00","close":"18:00"},"friday":{"enabled":true,"open":"09:00","close":"18:00"},"saturday":{"enabled":false,"open":"09:00","close":"18:00"},"sunday":{"enabled":false,"open":"09:00","close":"18:00"}}',
    'We are currently offline. Please leave us a message later.',
    1,
    'Need help?',
    'Chat with our team on WhatsApp.',
    2,
    '/* Example: .ctcw-widget { border-radius: 999px; } */',
    '<link rel="preconnect" href="https://fonts.googleapis.com">',
    '',
    ''
)
ON DUPLICATE KEY UPDATE
    widget_name = VALUES(widget_name),
    website_domain = VALUES(website_domain),
    allow_www = VALUES(allow_www),
    allow_subdomains = VALUES(allow_subdomains),
    domain_lock_enabled = VALUES(domain_lock_enabled),
    strict_domain_check = VALUES(strict_domain_check),
    updated_at = CURRENT_TIMESTAMP;
